name: dispatch build image

on:
  workflow_dispatch:
    inputs:
      branch:
        type: string
        required: true
        description: target branch
      tag:
        type: string
        required: true
        description: docker image tag

concurrency:
  group: build-${{ github.ref }}

jobs:
  build_amd64:
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    steps:
      - uses: joelwmale/webhook-action@2.1.0
        with:
          url: https://mstdn.plusminus.io/api/v1/statuses
          headers: '{"Authorization": "Bearer ${{ secrets.MASTODON_TOKEN }}"}'
          body: '{"status": ":loading: ğ™—ğ™ªğ™ğ™¡ğ™™ ğ™¨ğ™©ğ™–ğ™§ğ™©\n\ndocker image: plusminusio/paon:${{ github.event.inputs.tag }}\nworkflow: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"}'

      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}
          fetch-depth: 0

      - uses: docker/login-action@v2
        with:
          username: mohemohe
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/build-push-action@v4
        with:
          push: true
          tags: plusminusio/paon:${{ github.event.inputs.tag }}

      - if: success()
        uses: joelwmale/webhook-action@2.1.0
        with:
          url: https://mstdn.plusminus.io/api/v1/statuses
          headers: '{"Authorization": "Bearer ${{ secrets.MASTODON_TOKEN }}"}'
          body: '{"status": "â˜ºï¸ ğ™—ğ™ªğ™ğ™¡ğ™™ ğ™¨ğ™ªğ™˜ğ™˜ğ™šğ™¨ğ™¨\n\ndocker image: plusminusio/paon:${{ github.event.inputs.tag }}\nworkflow: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"}'

      - if: failure()
        uses: joelwmale/webhook-action@2.1.0
        with:
          url: https://mstdn.plusminus.io/api/v1/statuses
          headers: '{"Authorization": "Bearer ${{ secrets.MASTODON_TOKEN }}"}'
          body: '{"status": "ğŸ˜© ğ™—ğ™ªğ™ğ™¡ğ™™ ğ™›ğ™–ğ™ğ™¡ğ™ªğ™§ğ™š\n\ndocker image: plusminusio/paon:${{ github.event.inputs.tag }}\nworkflow: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"}'

  build_arm64:
    runs-on: ubuntu-24.04-arm
    timeout-minutes: 30
    steps:
      - uses: joelwmale/webhook-action@2.1.0
        with:
          url: https://mstdn.plusminus.io/api/v1/statuses
          headers: '{"Authorization": "Bearer ${{ secrets.MASTODON_TOKEN }}"}'
          body: '{"status": ":loading: ğ™—ğ™ªğ™ğ™¡ğ™™ ğ™¨ğ™©ğ™–ğ™§ğ™©\n\ndocker image: plusminusio/paon:${{ github.event.inputs.tag }}-arm64\nworkflow: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"}'

      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}
          fetch-depth: 0

      - uses: docker/login-action@v2
        with:
          username: mohemohe
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/build-push-action@v4
        with:
          push: true
          tags: plusminusio/paon:${{ github.event.inputs.tag }}-arm64

      - if: success()
        uses: joelwmale/webhook-action@2.1.0
        with:
          url: https://mstdn.plusminus.io/api/v1/statuses
          headers: '{"Authorization": "Bearer ${{ secrets.MASTODON_TOKEN }}"}'
          body: '{"status": "â˜ºï¸ ğ™—ğ™ªğ™ğ™¡ğ™™ ğ™¨ğ™ªğ™˜ğ™˜ğ™šğ™¨ğ™¨\n\ndocker image: plusminusio/paon:${{ github.event.inputs.tag }}-arm64\nworkflow: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"}'

      - if: failure()
        uses: joelwmale/webhook-action@2.1.0
        with:
          url: https://mstdn.plusminus.io/api/v1/statuses
          headers: '{"Authorization": "Bearer ${{ secrets.MASTODON_TOKEN }}"}'
          body: '{"status": "ğŸ˜© ğ™—ğ™ªğ™ğ™¡ğ™™ ğ™›ğ™–ğ™ğ™¡ğ™ªğ™§ğ™š\n\ndocker image: plusminusio/paon:${{ github.event.inputs.tag }}-arm64\nworkflow: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"}'
